spring.application.name=recordatorios-esp32
spring.datasource.url=aws-0-ca-central-1.pooler.supabase.com
spring.datasource.username=postgres.kjkaqilwznbctorfxjwe
spring.datasource.password=nosecuales123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect